In [22]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [23]:
data = pd.read_csv('mnist_train.csv')

In [24]:
data.head()

5  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.608  0.609  0.610  \
0  0  0    0    0    0    0    0    0    0    0  ...        0      0      0   
1  4  0    0    0    0    0    0    0    0    0  ...        0      0      0   
2  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   
3  9  0    0    0    0    0    0    0    0    0  ...        0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...        0      0      0   

   0.611  0.612  0.613  0.614  0.615  0.616  0.617  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [25]:
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [26]:
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

y = data.iloc[:,0].values

In [30]:
df_y = keras.utils.to_categorical(y,num_classes=10)

In [31]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [32]:
y

array([0, 4, 1, ..., 5, 6, 8])

In [33]:
df_y

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [35]:
df_x.shape

(59999, 28, 28, 1)

In [37]:
x_train, x_test, y_train = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

ValueError: too many values to unpack (expected 3)

In [41]:
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.complie(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

SyntaxError: positional argument follows keyword argument (<ipython-input-41-709bf8e2b3e9>, line 2)

In [ ]:
model.summary()

In [ ]:
model.fit(x_train,y_train,validation_data=(x_test,y_test))

model.evaluate(x_test,y_test)